joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

base_laser_controller:
    type: effort_controllers/JointPositionController
    joint: R283_hokuyo_laser1_joint
    pid: { p: 10.0, i: 0.01, d: 1.0 }

tilt_laser_controller:
    type: effort_controllers/JointPositionController
    joint: R313_hokuyo_laser2_joint
    pid: { p: 1.0, i: 0.01, d: 0.1 }

left_wheel_controller:
    type: effort_controllers/JointPositionController
    joint: segway_left_wheel_joint
    pid: { p: 10.0, i: 0.01, d: 2.0 }

right_wheel_controller:
    type: effort_controllers/JointPositionController
    joint: segway_right_wheel_joint
    pid: { p: 10.0, i: 0.01, d: 2.0 }
