TrajectoryPlannerROS:
    transform_tolerance: 0.3
    sim_time: 3.0
    sim_granularity: 0.10
    dwa: false
    vx_samples: 3
    vtheta_samples: 20
    max_vel_x: 0.6
    min_vel_x: 0.2
    max_vel_theta: 0.2
    min_vel_theta: -0.2
    min_in_place_vel_theta: 0.2
    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 0.2
    gdist_scale: 0.8
    pdist_scale: 2.0
    occdist_scale: 0.1
    heading_lookahead: 0.325
    oscillation_reset_dist: 0.05
    holonomic_robot: false
    acc_lim_theta: 0.3
    acc_lim_x: 2.5
    acc_lim_y: 2.5
    latch_xy_goal_tolerance: true
    escape_vel: -0.3

PDPlannerROS:
    transform_tolerance: 0.3
    sim_time: 0.2
    sim_granularity: 0.1
    dwa: false
    vx_samples: 3
    vtheta_samples: 20
    max_vel_x: 0.6
    min_vel_x: 0.2
    max_vel_theta: 0.2
    min_vel_theta: -0.2
    min_in_place_vel_theta: 0.2
    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 0.05
    gdist_scale: 0.8
    pdist_scale: 2.0
    occdist_scale: 0.1
    heading_lookahead: 0.325
    oscillation_reset_dist: 0.05
    holonomic_robot: false
    acc_lim_theta: 0.3
    acc_lim_x: 2.5
    acc_lim_y: 2.5
    latch_xy_goal_tolerance: true
    escape_vel: -0.3
    global_frame_id: odom
    goal_distance_bias: 0.8
    path_distance_bias: 0.9
    heading_lookahead: 0.325
    heading_scoring: false
    heading_scoring_timestep: 0.8
    holonomic_robot: false
    latch_xy_goal_tolerance: false
    meter_scoring: false
    prune_plan: true
    publish_cost_grid_pc: false
    y_vels: [-0.3, -0.1, 0.1, 0.3]  # unused unless holonomic_robot == true
    path_p: 2.0
    path_d: 7.0
