observation_sources: base_scan tilt_scan

base_scan: {
    data_type: LaserScan,
    expected_update_rate: 2.0,
    observation_persistence: 0.0,
    marking: true,
    clearing: true,
    max_obstacle_height: 1.0,
    min_obstacle_height: 0.1 }

tilt_scan: {
    data_type: LaserScan,
    expected_update_rate: 2.0,
    observation_persistence: 0.5,
    marking: true,
    clearing: true,
    max_obstacle_height: 1.0,
    min_obstacle_height: 0.3 }
