map_type: voxel
origin_z: 0.0
z_resolution: 0.2
z_voxels: 10
unknown_threshold: 10
mark_threshold: 0

transform_tolerance: 0.3
obstacle_range: 3.0
max_obstacle_height: 2.0
raytrace_range: 5.0
footprint: [[0.55, 0.16], [0.25, 0.55], [-0.25, 0.55], [-0.50, 0.20], [-0.85, 0.20], [-0.85, -0.20], [-0.50, -0.20], [-0.25, -0.55], [0.25, -0.55], [0.55, -0.16]]
footprint_padding: 0.3
inflation_radius: 2.0
cost_scaling_factor: 10.0
lethal_cost_threshold: 100
