### modified parameters ###

min_particles: 500
kld_err: 0.05
update_min_a: 0.1
resample_interval: 1
gui_publish_rate: 10.0

laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_rand: 0.5
laser_likelihood_max_dist: 0.6

odom_alpha1: 5.0
odom_alpha2: 0.4
odom_alpha3: 0.6
odom_alpha5: 0.1
base_frame_id: base_footprint

### explicit defaults (overrides are commented out) ###

#min_particles: 100
max_particles: 5000
#kld_err: 0.01
kld_z: 0.99
#update_min_a: 0.523599              # pi / 6
update_min_d: 0.2
transform_tolerance: 0.1
#resample_interval: 2
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0
initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0
initial_cov_xx: 0.25                # 0.5^2
initial_cov_yy: 0.25                # 0.5^2
initial_cov_aa: 0.068538919452009   # (pi/12)^2
gui_publish_rate: -1.0             # (disabled)
save_pose_rate: 0.5
use_map_topic: false
first_map_only: false

laser_min_range: -1.0
laser_max_range: -1.0
laser_max_beams: 30
#laser_z_hit: 0.95
#laser_z_short: 0.1
laser_z_max: 0.05
#laser_z_rand: 0.05
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
#laser_likelihood_max_dist: 2.0 meters
laser_model_type: likelihood_field

odom_model_type: diff
#odom_alpha1: 0.2
#odom_alpha2: 0.2
#odom_alpha3: 0.2
odom_alpha4: 0.2
#odom_alpha5: 0.2
odom_frame_id: odom                 # odom_combined
#base_frame_id: base_link
global_frame_id: map
