TrajectoryPlannerROS:
    acc_lim_theta: 0.3
    max_vel_x: 0.6
    min_vel_x: 0.2
    max_vel_theta: 0.2
    min_vel_theta: -0.2
    min_in_place_vel_theta: 0.2
    escape_vel: -0.3
    holonomic_robot: false
#    yaw_goal_tolerance: 0.5
#    xy_goal_tolerance: 0.8
    latch_xy_goal_tolerance: false
    sim_time: 3.0
    sim_granularity: 0.10
#    path_distance_bias: 4.8
    occdist_scale: 0.1
    dwa: false

### explicit defaults ###

#TrajectoryPlannerROS:
    acc_lim_x: 2.5
    acc_lim_y: 2.5
#    acc_lim_theta: 3.2
#    max_vel_x: 0.5
#    min_vel_x: -1.0
#    max_vel_theta: 1.0
#    min_vel_theta: -1.0
#    min_in_place_vel_theta: 0.4
#    escape_vel: -0.1
#    holonomic_robot: true
    y_vels: [-0.3, -0.1, 0.1, 0.3]  # unused unless holonomic_robot == true
    yaw_goal_tolerance: 0.05
    xy_goal_tolerance: 0.1
#    latch_xy_goal_tolerance: false
#    sim_time: 1.0
#    sim_granularity: 0.025
#    angular_sim_granularity: # inherits sim_granularity by default
    vx_samples: 3
    vtheta_samples: 20
#     controller_frequency: # inherits controller_frequency in move_base ns
    meter_scoring: false

    path_distance_bias: 0.6
    goal_distance_bias: 0.8
#    occdist_scale: 0.01

    heading_lookahead: 0.325
    heading_scoring: false
    heading_scoring_timestep: 0.8

#    dwa: true

    publish_cost_grid_pc: false
    global_frame_id: odom

    oscillation_reset_dist: 0.05
    prune_plan: true

    # hidden or outdated documentation...
#    stop_time_buffer: 0.2
#    escape_reset_dist: 0.10
#    escape_reset_theta: M_PI_4
#    world_model: costmap
#    point_grid:
#        max_sensor_range: 2.0
#        min_pt_separation: 0.01
#        max_obstacle_height: 2.0
#        grid_resolution: 0.2
