### modified parameters ###

global_costmap:
    update_frequency: 0.5
    publish_frequency: 1.0
    inflation_radius: 0.6
    unknown_cost_value: 255

    map_type: costmap
    track_unknown_space: true

    footprint_padding: 0.8

### explicit defaults ###

#global_costmap: # apparently redefining the namespace is bad
#    global_frame: /map             # inherited
#    robot_base_frame: base_link    # inherited
#    transform_tolerance:           # inherited
#    update_frequency: 5.0
#    publish_frequency: 0.0
#    max_obstacle_height            # inherited
#    obstacle_range                 # inherited
#    raytrace_range                 # inherited
#    cost_scaling_factor            # inherited
#    inflation_radius: 0.55
#    footprint: []                  # inherited
#    robot_radius: 0.46             # inherited
#    observation_sources: ""        # inherited
    static_map: true
    rolling_window: false
#    unknown_cost_value: 0
    publish_voxel_map: false
#    lethal_cost_threshold: 100     # inherited
#    map_topic: map                 # inherited
    width: 10                       # unused while static_map == true
    height: 10                      # unused while static_map == true
    resolution: 0.05                # unused while static_map == true
    origin_x: 0.0                   # unused while static_map == true
    origin_y: 0.0                   # unused while static_map == true
#    map_type: voxel
    origin_z: 0.0                                       # unused if map_type = costmap
    z_resolution: 0.2                                   # unused if map_type = costmap
    z_voxels: 10                                        # unused if map_type = costmap
#    unknown_threshold: inherits 'z_voxels' by default  # unused if map_type = costmap
    mark_threshold: 0                                   # unused if map_type = costmap
#    track_unknown_space: false                         # unused if map_type == voxel
#    footprint_padding: 0.01