### modified parameters ###

robot_base_frame: base_footprint
transform_tolerance: 0.3
obstacle_range: 3.0                 # see comment in defaults region
raytrace_range: 5.0                 # see comment in defaults region

footprint: [
    [ 0.55,  0.16],
    [ 0.25,  0.55],
    [-0.25,  0.55],
    [-0.50,  0.20],
    [-0.85,  0.20],
    [-0.85, -0.20],
    [-0.50, -0.20],
    [-0.25, -0.55],
    [ 0.25, -0.55],
    [ 0.55, -0.16]
]

observation_sources: base_scan

base_scan: {
#    topic: base_scan
#    sensor_frame: ""
    observation_persistence: 0.0,
    expected_update_rate: 2.0,
    data_type: LaserScan,
    clearing: true,
    marking: true,
    max_obstacle_height: 1.0,
    min_obstacle_height: 0.08
#    obstacle_range: 2.5
#    raytrace_range: 3.0
}

lethal_cost_threshold: 50

### explicit defaults ###

global_frame: /map
#robot_base_frame: base_link
#transform_tolerance: 0.2
#update_frequency: 5.0              # overridden
#publish_frequency: 0.0             # overridden
max_obstacle_height: 2.0
#obstacle_range: 2.5                # doesn't look like the global version of this parameter does anything
#raytrace_range: 3.0                # doesn't look like the global version of this parameter does anything
cost_scaling_factor: 10.0
#inflation_radius: 0.55             # overridden
#footprint: []
robot_radius: 0.46                  # overridden by 'footprint'
#observation_sources: ""
#static_map: true                   # overridden
#rolling_window: false              # overridden
#unknown_cost_value: 0              # overridden
#publish_voxel_map: false           # overridden
#lethal_cost_threshold: 100
map_topic: map
#width : 10                         # overriden - unused while static_map == true
#height : 10                        # overriden - unused while static_map == true
#resolution : 0.05                  # overriden - unused while static_map == true
#origin_x : 0.0                     # overriden - unused while static_map == true
#origin_y : 0.0                     # overriden - unused while static_map == true
#map_type: voxel                    # overridden
#origin_z: 0.0                      # overridden
#z_resolution: 0.2                  # overridden
#z_voxels: 10                       # overridden
#unknown_threshold:                 # overridden
#mark_threshold: 0                  # overridden
#track_unknown_space: false         # overridden
#footprint_padding: 0.01            # overridden
save_debug_pgm: false               # hurray for hidden parameter
